### ISSUE TITLE
Test passes successfully but keeps failing in circleCi 

### ISSUE THREAD

**Issue by khalidNC** [kindlyops/despite#29]
Keeps failing in circleCi with below error; would be very helpful if anyone can come up with the solutions. Thanks.

"
unknown command: Cannot call non W3C standard command while in W3C mode
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '108720a4f8ab', ip: '172.24.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '1.8.0_212'
Driver info: driver.version: unknown
[chrome #0-0] Error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
"

**Comment by statik** [comment]
Hi @khalidNC, I think this issue might be opened against the wrong repo?
