### ISSUE TITLE
Fix tests failing in CircleCI (but passing locally)

### ISSUE THREAD

**Issue by statik** [kindlyops/despite#7]
Mysteriously, make test passes locally and fails on CircleCI.
`make test` is running `make inner-test` under docker-compose, so the environments between local and CircleCI should be identical. Something must be different - finding out what is the mystery to solve.

**Comment by statik** [comment]
This is fixed now, I had a thinko about how glide vendoring works. The src isn't in the vendor directories, so we needed a glide install command in the CircleCI build.

On reflection, this is a very nice design property of glide, because it will keep our PRs from being overly noisy when changing versions of dependencies.

**Comment by kindlyseth** [comment]
But it will cause your builds to fail when a dependency goes away or the network to them goes away, if I understand correctly.

My strategy for dealing with this (usually when committing javascript dependencies or build outputs) is to commit dependency updates in a separate commit that contains nothing else.
